version: "3.7"

volumes:
    psql:

services:
    database:
        image: postgres
        volumes:
            - /psql/:/var/lib/postgresql/data
        restart: always
        environment:
          POSTGRES_PASSWORD: '12345'
          POSTGRES_USER: postgres
        ports:
            - 1010:5432
